### ISSUE TITLE
quoting issue on config file path

### ISSUE THREAD

**Issue by brett** [edthedev/minion#36]
Since updating my repo with the December updates, minion cannot read an existing, readable config file apparently due to quoting issues.
```shell
[user@host]:~% minion dates .
Traceback (most recent call last):
  File "/home/user/bin/minion", line 370, in <module>
    brain.GLOBAL_SETTINGS = brain.get_settings(CONFIG_FILE)
  File "/home/user/src/git/minion/brain_of_minion.py", line 113, in get_settings
    f = open(minion_file, 'w')
IOError: [Errno 2] No such file or directory: "'~/.minion'"
```

**Comment by edthedev** [comment]
My apologies. This fix made it into development, but had not been merged to master.
It is merged to master now. If you're using Pathogen or Vundle, you'll get the update next time you update.

Please re-open this issue if the problem re-occurs after the update.
