### ISSUE TITLE
Can't install...

### ISSUE THREAD

**Issue by kflak** [edthedev/minion#45]
Hi,

Fresh zsh user here, so please bear with me! I am getting this when following the installation instructions for antigen:
`(null): can't open file '/home/kf/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-edthedev-SLASH-minion.git/bin/minion.py': [Errno 2] No such file or directory`

Doing this on arch linux. Antigen does not create the repos folder, and stuffs edthedev/minion into the bundles folder instead. What to do?

**Comment by edthedev** [comment]
Sounds like we need to update the Antigen instructions.

Go ahead and use the bundles path you foubd instead of the repos one. It
sounds work fine.

If that works for you, let me know and I'll get the instructions updated.

Thanks for using Minion!

- Ed

**Comment by kflak** [comment]
Not working, unfortunately... If I do a clean reinstall (delete all files and running antigen in a new session), minion installs fine, but when running minion in cli I get the same error.

**Comment by edthedev** [comment]
Thanks for the bug report. Sorry we never resolved this.

Closing this as unsolved as latest version will requires PowerShell, and retires the Vim plugin (for now).
